---
title: "Dyslexia-Exercise"
author: "Dana Evelyn Jensen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE}
#Set Working Directory
setwd("C:\\Users\\danaj\\Documents\\GitHub\\Statistical_Methods_2")
library(pacman)
p_load(caret, e1071)

#load data
dyslexia <- read.table("dyslexia.txt", header=TRUE)

#change diagnosis to binary
dyslexia$Diagnosis[dyslexia$Diagnosis == 'noDyslexia'] <- '0'
dyslexia$Diagnosis[dyslexia$Diagnosis == 'Dyslexia'] <- '1'
dyslexia$Diagnosis <- as.numeric(dyslexia$Diagnosis)

#split text based on "task"
d_text = dyslexia[dyslexia$Task == "Text",]
d_words = dyslexia[dyslexia$Task == "Words",]
train <- rbind(d_text,d_words)
d_nonwords = dyslexia[dyslexia$Task == "Non-Words",]

#Make a training (model) subset and a testing (prediction) subset
train <- subset(train, select = c("Mistakes", "Diagnosis","Task"))
test <- subset(d_nonwords, select = c("Mistakes", "Diagnosis","Task"))

#make a logistic regression with one predictor(baseline)
m1 = glm(Diagnosis ~ Mistakes, data = train, family = "binomial")

#make a vector which predicts "response"
predictions = predict(m1, newdata = test, type = "response")

#if 'response' is <.5, label as 'noDyslexia', vice versa
predicted_diagnosis = ifelse(predictions<.5,"0","1")

#make a matrix to see how accurate predictions of diagnosis are
#dyslexia$Diagnosis <- as.factor(dyslexia$Diagnosis)
predicted_diagnosis <- data.frame(as.factor(predicted_diagnosis))
names(predicted_diagnosis) <- "Prediction"
predicted_diagnosis$Prediction <- as.factor(predicted_diagnosis$Prediction)

real <- data.frame(test$Diagnosis)
names(real) <- "Diagnosis"
real$Diagnosis <- as.factor(real$Diagnosis)

d.Matrix = confusionMatrix(predicted_diagnosis$Prediction, test$Diagnosis)

#multiple regression to test different hypothesis of predictors
m.Words = glm(Diagnosis ~ SyllableN, data = d.Words,family = "binomial")

#View coefficients, chisq, p-values, fischer values
summary(m.Words)
anova(m.Words,test = "Chisq")

m.Text = glm(Diagnosis ~ SyllableN + Duration, data = d.Text,family = "binomial")
summary(m.Text)
anova(m.Text, test = "Chisq")

m.non.Words = glm(Diagnosis ~ SyllableN + SyllablePerVoicedSecond, data = d.non.Words, family = "binomial")
summary(m.non.Words)
anova(m.non.Words, test = "Chisq")

caret::confusionMatrix(predicted_diagnosis,d.non.Words$Diagnosis,positive="Dyslexia")

```


